version: 2.1

workflows:

  myworkflows: 
    jobs:
      - configure_infrastructure

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "cd:ef:13:00:23:50:a0:72:72:2e:28:50:6b:0a:08:b9"
      - run: 
          name: Install dependencies
          command: |
            apk add --update ansible  # install the dependencies needed for your playbook
      - run:
          name: Configure server
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
          command: |
            ansible-playbook -i inventory.txt playbook.yml
